export const EFFECT_MANIFEST = Object.freeze({
  id: 'tone.filter',
  label: 'Filter',
  version: '1.0.1',
  inputParam: 'inputParam',
  dimensionId: 'EW::II',
  dimensionLabel: 'EW::II',
  defaults: Object.freeze({
    type: 'lowpass',
    frequency: 350,
    rolloff: -12,
    Q: 1,
    gain: 0,
  }),
  userParamSpec: Object.freeze({
    id: 'inputParam',
    label: 'Frequency',
    units: 'Hz',
    range: Object.freeze({ min: 20, max: 20000 }),
  }),
  modules: Object.freeze([
    Object.freeze({
      id: 'lowpass',
      label: 'Root Lowpass',
      description: 'Cutoff frequency (Hz)',
      dimension: 'EW::II',
      fixed: Object.freeze({ type: 'lowpass', rolloff: -24 }),
      target: 'frequency',
      valueRange: Object.freeze({ min: 20, max: 20000, units: 'Hz' }),
      initialRange: Object.freeze({ min: 20, max: 8000, equilibrium: 20000 }),
      control: Object.freeze({
        mode: 'audio-param',
        audioParam: 'frequency',
        provider: 'node',
        smoothing: Object.freeze({
          defaultRamp: 0.18,
          minRamp: 0.005,
          maxRamp: 0.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 20, max: 20000, transform: 'log' }),
      }),
    }),
    Object.freeze({
      id: 'highpass',
      label: 'Root Highpass',
      description: 'Cutoff frequency (Hz)',
      dimension: 'EW::II',
      fixed: Object.freeze({ type: 'highpass', rolloff: -12 }),
      target: 'frequency',
      valueRange: Object.freeze({ min: 20, max: 20000, units: 'Hz' }),
      initialRange: Object.freeze({ min: 3000, max: 18000, equilibrium: 20 }),
      control: Object.freeze({
        mode: 'audio-param',
        audioParam: 'frequency',
        provider: 'node',
        smoothing: Object.freeze({
          defaultRamp: 0.18,
          minRamp: 0.005,
          maxRamp: 0.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 20, max: 20000, transform: 'log' }),
      }),
    }),
    Object.freeze({
      id: 'bandpass',
      label: 'Root Bandpass',
      description: 'Center frequency (Hz)',
      dimension: 'EW::II',
      fixed: Object.freeze({ type: 'bandpass', rolloff: -48 }),
      target: 'frequency',
      valueRange: Object.freeze({ min: 20, max: 20000, units: 'Hz' }),
      initialRange: Object.freeze({ min: 300, max: 10000, equilibrium: 800 }),
      control: Object.freeze({
        mode: 'audio-param',
        audioParam: 'frequency',
        provider: 'node',
        smoothing: Object.freeze({
          defaultRamp: 0.18,
          minRamp: 0.005,
          maxRamp: 0.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 20, max: 20000, transform: 'log' }),
      }),
    }),
  ]),
});

export default EFFECT_MANIFEST;
