export const EFFECT_MANIFEST = Object.freeze({
  id: 'tone.timeReverse',
  label: 'Time Reverse',
  version: '1.0.0',
  inputParam: 'timeReverse',
  dimensionId: 'EW::I',
  dimensionLabel: 'EW::I',
  defaults: Object.freeze({
    playbackRate: 1,
    reverse: false,
  }),
  userParamSpec: Object.freeze({
    id: 'timeReverse',
    label: 'Reverse Control',
    units: '%',
    range: Object.freeze({ min: -100, max: 100, equilibrium: 0 }),
  }),
  modules: Object.freeze([
    Object.freeze({
      id: 'reverseTempoFine',
      engineRequirement: 'prebuffer-required',
      label: 'Reverse Tempo Fine (±16%)',
      description: 'Continuous playback direction control up to ±16% speed.',
      dimension: 'EW::I',
      target: 'timeReverse',
      valueRange: Object.freeze({ min: -16, max: 16, equilibrium: 0, units: '%' }),
      initialRange: Object.freeze({ min: -16, max: 16, equilibrium: 0 }),
      control: Object.freeze({
        mode: 'hybrid',
        audioParam: 'playbackRate',
        provider: 'playbackController',
        smoothing: Object.freeze({
          defaultRamp: 0.12,
          minRamp: 0.02,
          maxRamp: 1.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 0.84, max: 1.16, transform: 'linear' }),
        secondaryParameters: Object.freeze(['reverse']),
      }),
      segments: Object.freeze({
        negative: Object.freeze({
          id: 'reverseTempoFine::reverse',
          label: 'Reverse',
          description: '0→0.5 drives reverse playback up to -16%.',
          flags: Object.freeze({ reverse: true }),
        }),
        positive: Object.freeze({
          id: 'reverseTempoFine::forward',
          label: 'Forward',
          description: '0.5→1 drives forward playback up to +16%.',
          flags: Object.freeze({ reverse: false }),
        }),
      }),
    }),
    Object.freeze({
      id: 'reverseTempoWide',
      engineRequirement: 'prebuffer-required',
      label: 'Reverse Tempo Wide (±100%)',
      description: 'Continuous reverse/forward sweep up to ±100% speed.',
      dimension: 'EW::I',
      target: 'timeReverse',
      valueRange: Object.freeze({ min: -100, max: 100, equilibrium: 0, units: '%' }),
      initialRange: Object.freeze({ min: -100, max: 100, equilibrium: 0 }),
      control: Object.freeze({
        mode: 'hybrid',
        audioParam: 'playbackRate',
        provider: 'playbackController',
        smoothing: Object.freeze({
          defaultRamp: 0.15,
          minRamp: 0.02,
          maxRamp: 1.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 0, max: 2, transform: 'linear' }),
        secondaryParameters: Object.freeze(['reverse']),
      }),
      segments: Object.freeze({
        negative: Object.freeze({
          id: 'reverseTempoWide::reverse',
          label: 'Reverse',
          description: '0→0.5 sweeps reverse playback up to -100%.',
          flags: Object.freeze({ reverse: true }),
        }),
        positive: Object.freeze({
          id: 'reverseTempoWide::forward',
          label: 'Forward',
          description: '0.5→1 sweeps forward playback up to +100%.',
          flags: Object.freeze({ reverse: false }),
        }),
      }),
    }),
    Object.freeze({
      id: 'reversePitchFine',
      engineRequirement: 'prebuffer-required',
      label: 'Reverse Pitch Fine (±12st)',
      description: 'Quantized semitone stepping with reverse on the negative side.',
      dimension: 'EW::I',
      target: 'timeReverse',
      valueRange: Object.freeze({
        min: -12,
        max: 12,
        equilibrium: 0,
        units: 'st',
        quantize: Object.freeze({ step: 1, unit: 'st' }),
      }),
      initialRange: Object.freeze({ min: -12, max: 12, equilibrium: 0 }),
      control: Object.freeze({
        mode: 'hybrid',
        audioParam: 'playbackRate',
        provider: 'playbackController',
        smoothing: Object.freeze({
          defaultRamp: 0.12,
          minRamp: 0.02,
          maxRamp: 1.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 0.25, max: 4, transform: 'exponential' }),
        secondaryParameters: Object.freeze(['reverse']),
      }),
      segments: Object.freeze({
        negative: Object.freeze({
          id: 'reversePitchFine::reverse',
          label: 'Reverse Semitone Steps',
          description: '0→0.5 snaps through -12…0 semitone steps with reverse playback.',
          flags: Object.freeze({ reverse: true }),
        }),
        positive: Object.freeze({
          id: 'reversePitchFine::forward',
          label: 'Forward Semitone Steps',
          description: '0.5→1 snaps through +0…+12 semitone steps forward.',
          flags: Object.freeze({ reverse: false }),
        }),
      }),
    }),
    Object.freeze({
      id: 'reversePitchWide',
      engineRequirement: 'prebuffer-required',
      label: 'Reverse Pitch Wide (±24st)',
      description: 'Extended semitone stepping with reverse on negative values.',
      dimension: 'EW::I',
      target: 'timeReverse',
      valueRange: Object.freeze({
        min: -24,
        max: 24,
        equilibrium: 0,
        units: 'st',
        quantize: Object.freeze({ step: 1, unit: 'st' }),
      }),
      initialRange: Object.freeze({ min: -24, max: 24, equilibrium: 0 }),
      control: Object.freeze({
        mode: 'hybrid',
        audioParam: 'playbackRate',
        provider: 'playbackController',
        smoothing: Object.freeze({
          defaultRamp: 0.15,
          minRamp: 0.02,
          maxRamp: 1.5,
          curve: 'linear',
        }),
        signalRange: Object.freeze({ min: 0.1, max: 8, transform: 'exponential' }),
        secondaryParameters: Object.freeze(['reverse']),
      }),
      segments: Object.freeze({
        negative: Object.freeze({
          id: 'reversePitchWide::reverse',
          label: 'Reverse Semitone Steps',
          description: '0→0.5 snaps through -24…0 semitone steps with reverse playback.',
          flags: Object.freeze({ reverse: true }),
        }),
        positive: Object.freeze({
          id: 'reversePitchWide::forward',
          label: 'Forward Semitone Steps',
          description: '0.5→1 snaps through +0…+24 semitone steps forward.',
          flags: Object.freeze({ reverse: false }),
        }),
      }),
    }),
  ]),
});

export default EFFECT_MANIFEST;
